# Generated by Django 4.2.6 on 2023-10-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NasaJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('explanation', models.TextField(max_length=2000)),
                ('hdurl', models.CharField(max_length=200)),
                ('mediaType', models.CharField(max_length=20)),
                ('serviceVersion', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
